name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerability
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: 0a1d07e0-aeb7-46eb-8f03-92dd489b1628
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ SYNK_SECRETS.SYNK_TOKEN }}
        with:
          image: alpine/helm
