name: Github-Act-CLI
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      run: |
        echo "Ragu Test"
        pwd
        ls -ltra
